language: node_js
node_js:
  - "5"
script:
  - npm run check
after_success:
  - npm run coveralls
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
